export * from './dictionaryEntries.service';
import { DictionaryEntriesService } from './dictionaryEntries.service';
export * from './lemmatron.service';
import { LemmatronService } from './lemmatron.service';
export * from './lexiStats.service';
import { LexiStatsService } from './lexiStats.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './theSentenceDictionary.service';
import { TheSentenceDictionaryService } from './theSentenceDictionary.service';
export * from './thesaurus.service';
import { ThesaurusService } from './thesaurus.service';
export * from './translation.service';
import { TranslationService } from './translation.service';
export * from './utility.service';
import { UtilityService } from './utility.service';
export * from './wordlist.service';
import { WordlistService } from './wordlist.service';
export const APIS = [DictionaryEntriesService, LemmatronService, LexiStatsService, SearchService, TheSentenceDictionaryService, ThesaurusService, TranslationService, UtilityService, WordlistService];
