/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Wordlist } from '../model/wordlist';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SearchService {

    protected basePath = 'https://od-api-demo.oxforddictionaries.com:443/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieve possible matches to input
     *  Use this to retrieve possible [headword](documentation/glossary?term&#x3D;headword) matches for a given string of text. The results are culculated using headword matching, fuzzy matching, and [lemmatization](documentation/glossary?term&#x3D;lemma)     &lt;div id&#x3D;\&quot;search\&quot;&gt;&lt;/div&gt; 
     * @param sourceLang IANA language code
     * @param appId App ID Authentication Parameter
     * @param appKey App Key Authentication Parameter
     * @param q Search string
     * @param prefix Set prefix to true if you&#39;d like to get results only starting with search string.
     * @param regions If searching in English, filter words with specific region(s) either &#39;us&#39; or &#39;gb&#39;.
     * @param limit Limit the number of results per response. Default and maximum limit is 5000.
     * @param offset Offset the start number of the result.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchSourceLangGet(sourceLang: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'body', reportProgress?: boolean): Observable<Wordlist>;
    public searchSourceLangGet(sourceLang: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Wordlist>>;
    public searchSourceLangGet(sourceLang: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Wordlist>>;
    public searchSourceLangGet(sourceLang: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (sourceLang === null || sourceLang === undefined) {
            throw new Error('Required parameter sourceLang was null or undefined when calling searchSourceLangGet.');
        }
        if (appId === null || appId === undefined) {
            throw new Error('Required parameter appId was null or undefined when calling searchSourceLangGet.');
        }
        if (appKey === null || appKey === undefined) {
            throw new Error('Required parameter appKey was null or undefined when calling searchSourceLangGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (q !== undefined) {
            queryParameters = queryParameters.set('q', <any>q);
        }
        if (prefix !== undefined) {
            queryParameters = queryParameters.set('prefix', <any>prefix);
        }
        if (regions !== undefined) {
            queryParameters = queryParameters.set('regions', <any>regions);
        }
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;
        if (appId !== undefined && appId !== null) {
            headers = headers.set('app_id', String(appId));
        }
        if (appKey !== undefined && appKey !== null) {
            headers = headers.set('app_key', String(appKey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Wordlist>(`${this.basePath}/search/${encodeURIComponent(String(sourceLang))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve possible translation matches to input
     *  Use this to find matches in our translation dictionaries.    &lt;div id&#x3D;\&quot;search_translation\&quot;&gt;&lt;/div&gt; 
     * @param sourceSearchLanguage IANA language code
     * @param targetSearchLanguage IANA language code
     * @param appId App ID Authentication Parameter
     * @param appKey App Key Authentication Parameter
     * @param q Search string.
     * @param prefix Set prefix to true if you&#39;d like to get results only starting with search string.
     * @param regions Filter words with specific region(s) E.g., regions&#x3D;us. For now gb, us are available for en language.
     * @param limit Limit the number of results per response. Default and maximum limit is 5000.
     * @param offset Offset the start number of the result.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchSourceSearchLanguageTranslationstargetSearchLanguageGet(sourceSearchLanguage: string, targetSearchLanguage: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'body', reportProgress?: boolean): Observable<Wordlist>;
    public searchSourceSearchLanguageTranslationstargetSearchLanguageGet(sourceSearchLanguage: string, targetSearchLanguage: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Wordlist>>;
    public searchSourceSearchLanguageTranslationstargetSearchLanguageGet(sourceSearchLanguage: string, targetSearchLanguage: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Wordlist>>;
    public searchSourceSearchLanguageTranslationstargetSearchLanguageGet(sourceSearchLanguage: string, targetSearchLanguage: string, appId: string, appKey: string, q?: string, prefix?: boolean, regions?: string, limit?: string, offset?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (sourceSearchLanguage === null || sourceSearchLanguage === undefined) {
            throw new Error('Required parameter sourceSearchLanguage was null or undefined when calling searchSourceSearchLanguageTranslationstargetSearchLanguageGet.');
        }
        if (targetSearchLanguage === null || targetSearchLanguage === undefined) {
            throw new Error('Required parameter targetSearchLanguage was null or undefined when calling searchSourceSearchLanguageTranslationstargetSearchLanguageGet.');
        }
        if (appId === null || appId === undefined) {
            throw new Error('Required parameter appId was null or undefined when calling searchSourceSearchLanguageTranslationstargetSearchLanguageGet.');
        }
        if (appKey === null || appKey === undefined) {
            throw new Error('Required parameter appKey was null or undefined when calling searchSourceSearchLanguageTranslationstargetSearchLanguageGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (q !== undefined) {
            queryParameters = queryParameters.set('q', <any>q);
        }
        if (prefix !== undefined) {
            queryParameters = queryParameters.set('prefix', <any>prefix);
        }
        if (regions !== undefined) {
            queryParameters = queryParameters.set('regions', <any>regions);
        }
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;
        if (appId !== undefined && appId !== null) {
            headers = headers.set('app_id', String(appId));
        }
        if (appKey !== undefined && appKey !== null) {
            headers = headers.set('app_key', String(appKey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Wordlist>(`${this.basePath}/search/${encodeURIComponent(String(sourceSearchLanguage))}/translations=${encodeURIComponent(String(targetSearchLanguage))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
