/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SentencesResults } from '../model/sentencesResults';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TheSentenceDictionaryService {

    protected basePath = 'https://od-api-demo.oxforddictionaries.com:443/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieve corpus sentences for a given word
     *  Use this to retrieve sentences extracted from  corpora which show how a word is used in the language. This is available for English and Spanish. For English, the sentences are linked to the correct [sense](documentation/glossary?term&#x3D;sense) of the word in the dictionary. In Spanish, they are linked at the [headword](documentation/glossary?term&#x3D;headword) level.   &lt;div id&#x3D;\&quot;sentences\&quot;&gt;&lt;/div&gt; 
     * @param sourceLanguage IANA language code
     * @param wordId An Entry identifier. Case-sensitive.
     * @param appId App ID Authentication Parameter
     * @param appKey App Key Authentication Parameter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public entriesSourceLanguageWordIdSentencesGet(sourceLanguage: string, wordId: string, appId: string, appKey: string, observe?: 'body', reportProgress?: boolean): Observable<SentencesResults>;
    public entriesSourceLanguageWordIdSentencesGet(sourceLanguage: string, wordId: string, appId: string, appKey: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SentencesResults>>;
    public entriesSourceLanguageWordIdSentencesGet(sourceLanguage: string, wordId: string, appId: string, appKey: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SentencesResults>>;
    public entriesSourceLanguageWordIdSentencesGet(sourceLanguage: string, wordId: string, appId: string, appKey: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (sourceLanguage === null || sourceLanguage === undefined) {
            throw new Error('Required parameter sourceLanguage was null or undefined when calling entriesSourceLanguageWordIdSentencesGet.');
        }
        if (wordId === null || wordId === undefined) {
            throw new Error('Required parameter wordId was null or undefined when calling entriesSourceLanguageWordIdSentencesGet.');
        }
        if (appId === null || appId === undefined) {
            throw new Error('Required parameter appId was null or undefined when calling entriesSourceLanguageWordIdSentencesGet.');
        }
        if (appKey === null || appKey === undefined) {
            throw new Error('Required parameter appKey was null or undefined when calling entriesSourceLanguageWordIdSentencesGet.');
        }

        let headers = this.defaultHeaders;
        if (appId !== undefined && appId !== null) {
            headers = headers.set('app_id', String(appId));
        }
        if (appKey !== undefined && appKey !== null) {
            headers = headers.set('app_key', String(appKey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<SentencesResults>(`${this.basePath}/entries/${encodeURIComponent(String(sourceLanguage))}/${encodeURIComponent(String(wordId))}/sentences`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
