/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';


export interface ArrayOfRelatedEntriesInner {
    /**
     * A subject, discipline, or branch of knowledge particular to the Sense
     */
    domains?: Arrayofstrings;
    /**
     * The identifier of the word
     */
    id: string;
    /**
     * IANA language code specifying the language of the word
     */
    language?: string;
    /**
     * A particular area in which the pronunciation occurs, e.g. 'Great Britain'
     */
    regions?: Arrayofstrings;
    /**
     * A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
     */
    registers?: Arrayofstrings;
    text: string;
}
