/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArrayOfRelatedEntriesInner } from './arrayOfRelatedEntriesInner';


/**
 * A list of written or spoken words
 */
export interface ArrayOfRelatedEntries extends Array<ArrayOfRelatedEntriesInner> {
}
