/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategorizedTextListInner } from './categorizedTextListInner';


/**
 * various types of notes that appear
 */
export interface CategorizedTextList extends Array<CategorizedTextListInner> {
}
