/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CategorizedTextListInner {
    /**
     * The identifier of the word
     */
    id?: string;
    /**
     * A note text
     */
    text: string;
    /**
     * The descriptive category of the text
     */
    type: string;
}
