/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * cross references of a sense
 */
export interface CrossReferencesListInner {
    /**
     * The word id of cooccurrence
     */
    id: string;
    /**
     * The word of cooccurrence
     */
    text: string;
    /**
     * The type of relation between the two words. Possible values are 'close match', 'related', 'see also', 'variant spelling', and 'abbreviation' in case of crossreferences, or 'pre', 'post' in case of collocates.
     */
    type: string;
}
