/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CrossReferencesListInner } from './crossReferencesListInner';


/**
 * A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.
 */
export interface CrossReferencesList extends Array<CrossReferencesListInner> {
}
