/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExamplesListInner } from './examplesListInner';


/**
 * A list of written or spoken rendering of examples of use of a word or text
 */
export interface ExamplesList extends Array<ExamplesListInner> {
}
