/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';
import { CategorizedTextList } from './categorizedTextList';
import { TranslationsList } from './translationsList';


export interface ExamplesListInner {
    /**
     * A list of statements of the exact meaning of a word
     */
    definitions?: Arrayofstrings;
    /**
     * A subject, discipline, or branch of knowledge particular to the Sense
     */
    domains?: Arrayofstrings;
    notes?: CategorizedTextList;
    /**
     * A particular area in which the pronunciation occurs, e.g. 'Great Britain'
     */
    regions?: Arrayofstrings;
    /**
     * A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
     */
    registers?: Arrayofstrings;
    /**
     * The list of sense identifiers related to the example. Provided in the sentences endpoint only.
     */
    senseIds?: Arrayofstrings;
    text: string;
    translations?: TranslationsList;
}
