/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GrammaticalFeaturesListInner } from './grammaticalFeaturesListInner';


/**
 * The different forms are correlated with meanings or functions which we text as 'features'
 */
export interface GrammaticalFeaturesList extends Array<GrammaticalFeaturesListInner> {
}
