/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LanguagesResults } from './languagesResults';


/**
 * Schema for the languages endpoint.
 */
export interface Languages {
    /**
     * Additional Information provided by OUP
     */
    metadata?: any;
    /**
     * A list of languages available.
     */
    results?: Array<LanguagesResults>;
}
