/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LanguagesSourceLanguage } from './languagesSourceLanguage';
import { LanguagesTargetLanguage } from './languagesTargetLanguage';


export interface LanguagesResults {
    /**
     * Name of region.
     */
    region?: string;
    /**
     * Name of source dictionary.
     */
    source?: string;
    sourceLanguage?: LanguagesSourceLanguage;
    targetLanguage?: LanguagesTargetLanguage;
    /**
     * whether monolingual or bilingual.
     */
    type?: LanguagesResults.TypeEnum;
}
export namespace LanguagesResults {
    export type TypeEnum = 'monolingual' | 'bilingual';
    export const TypeEnum = {
        Monolingual: 'monolingual' as TypeEnum,
        Bilingual: 'bilingual' as TypeEnum
    }
}
