/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GrammaticalFeaturesList } from './grammaticalFeaturesList';
import { InflectionsList } from './inflectionsList';


/**
 * Description of an entry for a particular part of speech and grammatical features
 */
export interface LemmatronLexicalEntry {
    grammaticalFeatures?: GrammaticalFeaturesList;
    /**
     * The canonical form of words for which the entry is an inflection
     */
    inflectionOf: InflectionsList;
    /**
     * IANA language code
     */
    language: string;
    /**
     * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
     */
    lexicalCategory: string;
    /**
     * A given written or spoken realisation of a an entry.
     */
    text: string;
}
