/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Ngrams matching the given options
 */
export interface NgramsResultResults {
    /**
     * The number of times the ngram (a sequence of n words) appears in the corpus
     */
    frequency: number;
    /**
     * A list of tokens
     */
    tokens: Array<string>;
}
