/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';


/**
 * A grouping of pronunciation information
 */
export interface PronunciationsListInner {
    /**
     * The URL of the sound file
     */
    audioFile?: string;
    /**
     * A local or regional variation where the pronunciation occurs, e.g. 'British English'
     */
    dialects?: Arrayofstrings;
    /**
     * The alphabetic system used to display the phonetic spelling
     */
    phoneticNotation?: string;
    /**
     * Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
     */
    phoneticSpelling?: string;
    /**
     * A particular area in which the pronunciation occurs, e.g. 'Great Britain'
     */
    regions?: Arrayofstrings;
}
