/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';


/**
 * Schema for region endpoint.
 */
export interface Regions {
    /**
     * Additional Information provided by OUP
     */
    metadata?: any;
    /**
     * A mapping of regions available.
     */
    results?: { [key: string]: Arrayofstrings; };
}
