/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExamplesList } from './examplesList';
import { GrammaticalFeaturesList } from './grammaticalFeaturesList';


/**
 * Description of an entry for a particular part of speech
 */
export interface SentencesLexicalEntry {
    grammaticalFeatures?: GrammaticalFeaturesList;
    /**
     * IANA language code
     */
    language: string;
    /**
     * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
     */
    lexicalCategory?: string;
    /**
     * A list of examples of use sentences
     */
    sentences: ExamplesList;
    /**
     * A given written or spoken realisation of a an entry.
     */
    text: string;
}
