/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatsWordResultListResults } from './statsWordResultListResults';


/**
 * Schema for lexi-stats results for a word/trueCase/lemma/lexicalCategory returned as a list of frequencies per wordform-trueCase-lemma-lexicalCategory entry.
 */
export interface StatsWordResultList {
    /**
     * Additional Information provided by OUP
     */
    metadata?: any;
    /**
     * A list of found words along with their frequencies
     */
    results?: Array<StatsWordResultListResults>;
}
