/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatsWordResultResult } from './statsWordResultResult';


/**
 * Schema for lexi-stats results for a word/trueCase/lemma/lexicalCategory returned as a frequency
 */
export interface StatsWordResult {
    /**
     * Additional Information provided by OUP
     */
    metadata?: any;
    result?: StatsWordResultResult;
}
