/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Statistical information about a word
 */
export interface StatsWordResultListResults {
    /**
     * The number of times a word appears in the entire corpus
     */
    frequency: number;
    /**
     * A lemma of the word.
     */
    lemma: string;
    /**
     * A lexical category such as 'verb' or 'noun'
     */
    lexicalCategory: string;
    /**
     * The number of times a word appears on average in 1 million words
     */
    normalizedFrequency: number;
    /**
     * A given written realisation of a an entry (e.g., \"lay\") usually lower case
     */
    trueCase: string;
    /**
     * A given written realisation of a an entry (e.g., \"lay\") preserving case
     */
    wordform: string;
}
