/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Link to a sense of a specific entry in the thesaurus Dictionary
 */
export interface ThesaurusLink {
    /**
     * identifier of a word
     */
    entryId: string;
    /**
     * identifier of a sense
     */
    senseId: string;
}
