/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';
import { ExamplesList } from './examplesList';
import { SynonymsAntonyms } from './synonymsAntonyms';


/**
 * A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
 */
export interface ThesaurusSense {
    /**
     * antonym of word
     */
    antonyms?: SynonymsAntonyms;
    /**
     * A subject, discipline, or branch of knowledge particular to the Sense
     */
    domains?: Arrayofstrings;
    examples?: ExamplesList;
    /**
     * The id of the sense that is required for the delete procedure
     */
    id?: string;
    /**
     * A particular area in which the Sense occurs, e.g. 'Great Britain'
     */
    regions?: Arrayofstrings;
    /**
     * A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
     */
    registers?: Arrayofstrings;
    /**
     * subsenses of word
     */
    subsenses?: Array<ThesaurusSense>;
    /**
     * synonym of word
     */
    synonyms?: SynonymsAntonyms;
}
