/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TranslationsListInner } from './translationsListInner';


/**
 * A list of written or spoken rendering of the meaning of a word or text in another language(s)
 */
export interface TranslationsList extends Array<TranslationsListInner> {
}
