/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UtilityLabelsResults } from './utilityLabelsResults';


/**
 * Schema for lexicalcategories, registers utility endpoints.
 */
export interface UtilityLabels {
    /**
     * Additional Information provided by OUP
     */
    metadata?: any;
    /**
     * Mapping of labels available.
     */
    results?: { [key: string]: UtilityLabelsResults; };
}
