/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * the list of labels for an object. Every object can be a lexical category, or a register, or a domain.
 */
export interface UtilityLabelsResults {
    /**
     * Label in English
     */
    en?: string;
}
