/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Arrayofstrings } from './arrayofstrings';


export interface VariantFormsListInner {
    /**
     * A particular area in which the variant form occurs, e.g. 'Great Britain'
     */
    regions?: Arrayofstrings;
    text: string;
}
